// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldszagprtplqmznissjk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxkc3phZ3BydHBscW16bmlzc2prIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMTgxNDYsImV4cCI6MjA3MTg5NDE0Nn0.NlP7csS85Rk5raY-h5cJ3KiKDxKLw4XXsCUXyBLN6VM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});